### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mrzv** [rubdos/libssh2pp#1]
Please add a license (ideally, something permissive, like MIT), so that it's clear under what conditions your code can be used.

**Comment by rubdos** [comment]
If LGPLv3 is permissive enough, I'd prefer that. Let me know if that's okay for you, I'll update the repo asap.

**Comment by mrzv** [comment]
LGPL makes things very complicated. Why not license under BSD, like libssh2 itself?

**Comment by rubdos** [comment]
What has LGPL that makes things complicated? I don't want someone to be able to use code that I wrote without having to contribute back. LGPL makes it perfectly fine to use my code in any proprietary application, as long as you contribute back changes to that single file.

**Comment by mrzv** [comment]
Well, let's see. Your library is a single header file, which means it's necessarily compiled in statically, which means any code that uses it has to be licensed under LGPL. One can work around this by splitting the header file into an actual dynamic library, but that defeats much of the advantage, and in my case it still wouldn't work because my employer doesn't let us release code under (L)GPL (only BSD, or something else permissive).

But I guess it doesn't really matter. What matters is that you've articulated the conditions under which your code can be used. The fact that they make it useless to me doesn't mean others won't find it useful. So it's all good; you can close this issue.

**Comment by rubdos** [comment]
Okay!
